include:
  - board: xiao_ble
    shield: MonoOwl_R rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: xiao_ble
    shield: MonoOwl_L rgbled_adapter
  - board: xiao_ble
    shield: settings_reset
