include:
  - board: xiao_ble rgbled_adapter
    shield: MonoOwl_R
    snippet: studio-rpc-usb-uart
  - board: xiao_ble rgbled_adapter
    shield: MonoOwl_L
  - board: xiao_ble
    shield: settings_reset